-- 테이블 생성
CREATE TABLE SPRING_BOARD (
	B_NUM NUMBER NOT NULL,
	B_NAME VARCHAR2(10) NOT NULL,
 	B_TITLE VARCHAR2(1000) NOT NULL,
 	B_CONTENT CLOB NOT NULL,
 	B_PWD VARCHAR2(18) NOT NULL,
 	B_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE SPRING_BOARD
ADD CONSTRAINT SPRING_BOARD_PK PRIMARY KEY(B_NUM);

COMMENT ON TABLE SPRING_BOARD IS '게시판 정보';
COMMENT ON COLUMN SPRING_BOARD.B_NUM IS '게시판 순번';
COMMENT ON COLUMN SPRING_BOARD.B_NAME IS '게시판 작성자';
COMMENT ON COLUMN SPRING_BOARD.B_TITLE IS '게시판 제목';
COMMENT ON COLUMN SPRING_BOARD.B_CONTENT IS '게시판 내용';
COMMENT ON COLUMN SPRING_BOARD.B_PWD IS '게시판 비밀번호';
COMMENT ON COLUMN SPRING_BOARD.B_DATE IS '게시판 등록일';

-- 게시판 테이블에 저장할 글번호 시퀀스
CREATE SEQUENCE SPRING_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

INSERT INTO SPRING_BOARD(B_NUM, B_NAME, B_TITLE, B_CONTENT, B_PWD, B_DATE)
VALUES(SPRING_BOARD_SEQ.NEXTVAL, '홍길동', 'mvc 게시판 작성', 'mvc 게시판 작성하기 예제입니다.', '1234', SYSDATE);

