/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-07-27 03:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.usermanage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>약관동의</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/include/css/bootstrap_intro.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/include/js/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/include/js/bootstrap.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t//체크박스 전체 선택\r\n");
      out.write("\t\t\t\t $(\"#check\").change(function(){\r\n");
      out.write("\t\t\t            var is_check = $(this).is(\":checked\");\r\n");
      out.write("\t\t\t            $(\".check1\").prop(\"checked\", is_check);\r\n");
      out.write("\t\t\t         });\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//비동의시 유효성체크\r\n");
      out.write("\t\t\t\t$('#next1').click(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(\"input[name='con_user']:checked\").val() == \"Y\") {\r\n");
      out.write("\t\t\t\t\t\t if($(\"input[name='con_per']:checked\").val() == \"Y\"){\r\n");
      out.write("\t\t\t\t\t\t\t location.href=\"/usermanage/join.do\";\r\n");
      out.write("\t\t\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"약관에 동의하지 않으시면 가입하실 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\talert(\"약관에 동의하지 않으시면 가입하실 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}); //end ready()\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\">약관동의</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"checkbox\" id=\"check\" value=\"Y\"/> \r\n");
      out.write("\t\t\t\t\t<label>약관 및 개인정보 동의 내용을 <br/>확인하였으며 아래 내용에 동의합니다.</label><br><br/><br/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"checkbox\" class=\"check1\" name=\"con_user\" value=\"Y\"/>\r\n");
      out.write("\t\t\t\t\t<label>개인정보 취급방침</label>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">[전문보기]</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"checkbox\" class=\"check1\" name=\"con_per\" value=\"Y\"/>\r\n");
      out.write("\t\t\t\t\t<label>홈페이지 이용약관</label>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal1\">[전문보기]</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label>*전문 보기 선택시 법정고지사항을 확인할수 있습니다.</label> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"button\" id=\"next1\" name=\"next1\" value=\"다음\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"myModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal content-->\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        <h4 class=\"modal-title\">개인정보 이용약관</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <p>1. 수집하는 개인정보의 항목 및 수집방법 \r\n");
      out.write("- 이용자는 회원가입을 하지 않더라도 원하는 정보를 검색하거나 컨텐츠 보기, 컨텐츠 공유 등 대부분의 회사 서비스 이용이 가능합니다.\r\n");
      out.write("- 이용자가 전체 기업정보, 즐겨찾기 등록, 투자이력 열람 등의 회원제 기반으로 제공되는 서비스를 이용하고자 하는 경우에는 회원가입이 필요합니다.\r\n");
      out.write("  가. 수집하는 개인정보의 항목 \r\n");
      out.write("1) 회사는 회원가입, 원활한 고객상담, 각종 서비스의 제공을 위해 최초 회원가입 당시 아래와 같은 개인정보를 수집하고 있습니다.\r\n");
      out.write("- 필수항목 : 이메일 주소, 비밀번호\r\n");
      out.write("2) 회사는 회원가입한 이용자의 투자서비스 제공을 위해 실명확인 및 계좌등록 등을 진행하고 있으며, 아래와 같은 개인정보를 수집하고 있습니다.\r\n");
      out.write("- 소득요건확인 또는 전문투자자 확인시(이하 ‘투자자 확인’) 필수항목 : 소득요건구비투자자 확인서류(금융소득명세서, 근로소득원칭징수영수증 등) 또는 전문투자자 확인서류(전문자격증, 전문투자자 확인증 등)\r\n");
      out.write("- 실명확인시 필수항목\r\n");
      out.write("가) 자연인 : 성명, 휴대폰번호, 주소, 신분증 사본, 주민등록번호 \r\n");
      out.write("나) 법인 : 법인명, 사업자등록번호, 법인등록번호, 법인 담당자 전화번호, 주사무소 소재지, 법인등기부등본, 대표자 신분증 사본\r\n");
      out.write("  - 계좌등록시 필수항목 : 본인의 증권계좌번호, 증권사\r\n");
      out.write("  - 청약증거금 납입시 필수항목 : 은행, 계좌번호, 고유식별번호\r\n");
      out.write("  (미성년자의 경우 법정대리인의 실명확인증표, 가족관계서류등 별도 서류)\r\n");
      out.write("3) 서비스 이용과정이나 사업처리 과정에서 아래와 같은 정보들이 자동으로 생성되어 수집될 수 있습니다. \r\n");
      out.write("  - 서비스 이용과정에서 이용자가 입력한 정보 및 작성한 저작물 \r\n");
      out.write("  - IP Address, 쿠키, 방문 일시, 서비스 이용 기록, 불량 이용 기록 \r\n");
      out.write("  나. 개인정보 수집방법 \r\n");
      out.write("회사는 다음과 같은 방법으로 개인정보를 수집합니다.\r\n");
      out.write("  - 홈페이지\r\n");
      out.write("  - 생성정보 수집 툴을 통한 수집\r\n");
      out.write("2. 개인정보의 수집 및 이용목적 \r\n");
      out.write("  가. 서비스 제공에 관한 계약 이행 및 서비스 제공에 따른 요금정산\r\n");
      out.write("  - 컨텐츠 제공, 온라인소액투자서비스 제공, 특정 맞춤 서비스 제공, 실명확인, 청약증거금 결제\r\n");
      out.write("  나. 회원관리\r\n");
      out.write("  - 회원제 서비스 이용 및 제한적 본인 확인제에 따른 본인확인, 개인식별, 불량회원(회사 이용약관 제11조 제1항 각 호에 해당하는 위반사유로 인한 영구이용정지 및 제19조 제2항에 따라 계약해지된 영구이용정지 회원)의 부정 이용방지와 비인가 사용방지, 가입의사 확인, 가입 및 가입횟수 제한, 분쟁 조정을 위한 기록보존, 불만처리 등 민원처리, 고지사항 전달\r\n");
      out.write("  다. 신규 서비스 개발 및 마케팅, 광고에 활용\r\n");
      out.write("  - 신규 서비스 개발 및 맞춤 서비스 제공, 통계학적 특성에 따른 서비스 제공 및 광고 게재, 서비스의 유효성 확인, 이벤트 및 광고성 정보 제공 및 참여기회 제공, 접속빈도 파악, 회원의 서비스이용에 대한 통계\r\n");
      out.write("3. 개인정보의 공유 및 제3자 제공 \r\n");
      out.write("회사는 이용자들의 개인정보를 \"2. 개인정보의 수집및 이용목적\"에서 고지한 범위내에서 사용하며, 이용자의 사전 동의 없이는 동 범위를 초과하여 이용하거나 이용자의 개인정보를 제3자에게 공개하지 않습니다. 다만, 법령의 규정에 의거하거나, 수사 목적으로 법령에 정해진 절차와 방법에 따라 수사기관의 요구가 있는 경우, 그리고 다음 경우에는 예외로 합니다. \r\n");
      out.write("1) 투자한도 확인\r\n");
      out.write("개인정보를 제공 받는 자 : 한국예탁결제원\r\n");
      out.write("제공하는 개인정보의 항목 : 투자자확인, 실명확인, 계좌등록 시 제공한 개인정보 일체\r\n");
      out.write("개인정보를 제공 받는 자의 개인정보 이용목적 : 투자한도 확인, 청약내역관리, 증권계좌 유효성 확인, 증권발행 및 배정내역관리\r\n");
      out.write("제공받은 개인정보의 이용기간 및 보유기간 : 10년\r\n");
      out.write("\r\n");
      out.write("2) 청약증거금 납입\r\n");
      out.write("개인정보를 제공 받는 자 : 금융결제원\r\n");
      out.write("제공하는 개인정보의 항목 : 청약금납입시 제공한 개인정보 일체\r\n");
      out.write("개인정보를 제공 받는 자의 개인정보 이용목적 : 비대면 실명확인, 청약증거금 관리 및 납입\r\n");
      out.write("제공받은 개인정보의 이용기간 및 보유기간 : 청약증거금 납입시부터 이체 완료시까지\r\n");
      out.write("4. 개인정보의 취급위탁 \r\n");
      out.write("회사는 서비스 향상을 위해서 귀하의 개인정보를 외부에 위탁하여 처리할 수 있습니다. \r\n");
      out.write("- 개인정보의 처리를 위탁하는 경우에는 미리 그 사실을 귀하에게 고지하고 동의를 받도록 하겠습니다. \r\n");
      out.write("- 개인정보의 처리를 위탁하는 경우에는 위탁계약 등을 통하여 서비스제공자의 개인정보보호 관련 지시엄수, 개인정보에 관한 비밀유지, 제3자 제공의 금지 및 사고시의 책임부담 등을 명확히 규정하고 당해 계약내용을 서면 또는 전자적으로 보관하겠습니다.\r\n");
      out.write("회사의 개인정보 위탁처리 기관 및 위탁업무 내용은 아래와 같습니다.\r\n");
      out.write("     (수탁업체: Amazon Web Services, Inc.) \r\n");
      out.write("    - 데이터베이스 관리, 유지관리 서비스, 서비스의 운영을 위한 이메일 전송\r\n");
      out.write("    (수탁업체: Google Analytics) \r\n");
      out.write("    - 서비스의 운영을 위한 데이터 애널리틱스 및 데이터 처리\r\n");
      out.write("5. 개인정보의 보유 및 이용기간 \r\n");
      out.write("1) 이용자의 개인정보는 원칙적으로 개인정보의 수집 및 이용목적이 달성되면 지체 없이 파기합니다. 다만, 상법, 자본시장과 금융투자에 관한 법률, 전자금융거래법, 특정 금융거래정보의 보고 및 이용에 관한 법률 등 관련법규상의 의무이행 및 금융감독원 기타 감독기관의 요청·명령에 따른 제출할 의무이행에 필요할 것으로 판단되는 정보에 대해서는 개인정보를 파기하지 아니하고 보유할 수 있습니다. \r\n");
      out.write("2) 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보존합니다.\r\n");
      out.write("    - 부정이용기록\r\n");
      out.write("     보존 이유 : 부정 이용 방지\r\n");
      out.write("     보존 기간 : 1년\r\n");
      out.write("    - 투자자확인, 실명확인 및 계좌등록에 관한 기록\r\n");
      out.write("     보존 이유 : 정보통신망 이용촉진 및 정보보호 등에 관한 법률\r\n");
      out.write("     보존 기간 : 1년(다만, 실명확인을 위한 이미지 파일은 확인 후 즉시 삭제함)\r\n");
      out.write("    - 전자금융거래의 종류 및 금액, 전자금융거래의 상대방에 관한 정보, 거래일시 등 전자금융기록\r\n");
      out.write("     보존 이유 : 전자금융거래법\r\n");
      out.write("     보존 기간 : 5년(다만, 건당 1만원 이하인 전자금융거래에 관한 기록은 1년간 보존)\r\n");
      out.write("    - 방문에 관한 기록\r\n");
      out.write("     보존 이유 : 통신비밀보호법\r\n");
      out.write("     보존 기간 : 3개월\r\n");
      out.write("6. 개인정보 파기절차 및 방법 \r\n");
      out.write("이용자의 개인정보는 원칙적으로 개인정보의 수집 및 이용목적이 달성되면 지체 없이 파기합니다.\r\n");
      out.write("회사의 개인정보 파기절차 및 방법은 다음과 같습니다.\r\n");
      out.write("  가. 파기절차\r\n");
      out.write("    - 이용자가 회원가입 등을 위해 입력한 정보는 목적이 달성된 후 별도의 DB로 옮겨져(종이의 경우 별도의 서류함) 내부 방침 및 기타 관련 법령에 의한 정보보호 사유에 따라(보유 및 이용기간 참조)일정 기간 저장된 후 파기됩니다. \r\n");
      out.write("    - 동 개인정보는 법률에 의한 경우가 아니고서는 보유되는 이외의 다른 목적으로 이용되지 않습니다.\r\n");
      out.write("  나. 파기방법\r\n");
      out.write("    - 종이에 출력된 개인정보는 분쇄기로 분쇄하거나 소각을 통하여 파기합니다.\r\n");
      out.write("    - 전자적 파일 형태로 저장된 개인정보는 기록을 재생할 수 없는 기술적 방법을 사용하여 삭제합니다.\r\n");
      out.write("7. 이용자 및 법정대리인의 권리와 그 행사방법 \r\n");
      out.write("    - 이용자 및 법정대리인은 언제든지 등록되어 있는 자신 혹은 당해 만14세 미만 아동의 개인정보를 조회하거나 수정할 수 있으며 가입해지를 요청할 수도 있습니다. \r\n");
      out.write("    - 이용자 혹은 당해 만 14세 미만 아동의 개인정보 조회, 수정을 위해서는 '개인정보변경'(또는 '회원정보수정' 등)을, 가입해지(동의철회)를 위해서는 \"회원탈퇴\"를 클릭하여 본인 확인 절차를 거치신 후 직접 열람, 정정 또는 탈퇴가 가능합니다. \r\n");
      out.write("    - 문의사항은 개인정보관리책임자에게 서면, 전화 또는 이메일로 연락하시면 지체 없이 조치하겠습니다. \r\n");
      out.write("    - 이용자가 개인정보의 오류에 대한 정정을 요청하신 경우에는 정정을 완료하기 전까지 당해 개인정보를 이용 또는 제공하지 않습니다. 또한 잘못된 개인정보를 제3 자에게 이미 제공한 경우에는 정정 처리결과를 제3자에게 지체 없이 통지하여 정정이 이루어지도록 하겠습니다. \r\n");
      out.write("    - 회사는 이용자 혹은 법정 대리인의 요청에 의해 해지 또는 삭제된 개인정보는 \"5. 개인정보의 보유 및 이용기간\"에 명시된 바에 따라 처리하고 그 외의 용도로 열람 또는 이용할 수 없도록 처리하고 있습니다.\r\n");
      out.write("8. 개인정보 자동 수집 장치의 설치·운영 및 거부에 관한 사항 \r\n");
      out.write("회사는 개인화되고 맞춤화된 서비스를 제공하기 위해서 이용자의 정보를 저장하고 수시로 불러오는 '쿠키(cookie)'를 사용합니다. 쿠키는 웹사이트를 운영하는데 이용되는 서버가 이용자의 브라우저에게 보내는 아주 작은 텍스트 파일로 이용자 컴퓨터의 하드디스크에 저장됩니다.  \r\n");
      out.write("\r\n");
      out.write("  가. 쿠키의 사용 목적\r\n");
      out.write("  - 이용자들의 로그인 및 최근접속기록을 토대로 유저간 상호 커뮤니케이션 시의 편리한 기능을 제공하기 위하여 활용됩니다.\r\n");
      out.write("  나. 쿠키의 설치/운영 및 거부\r\n");
      out.write("  - 이용자는 쿠키 설치에 대한 선택권을 가지고 있습니다. 따라서 이용자는 웹브라우저에서 옵션을 설정함으로써 모든 쿠키를 허용하거나, 쿠키가 저장될 때마다 확인을 거치거나, 아니면 모든 쿠키의 저장을 거부할 수도 있습니다.\r\n");
      out.write("  - 다만, 쿠키의 저장을 거부할 경우에는 이용에 어려움이 있을 수 있습니다.\r\n");
      out.write("  - 쿠키 설치 허용 여부를 지정하는 방법(Internet Explorer의 경우)\r\n");
      out.write("    ① [도구] 메뉴에서 [인터넷 옵션]을 선택합니다.\r\n");
      out.write("    ② [개인정보 탭]을 클릭합니다.\r\n");
      out.write("    ③ [개인정보취급 수준]을 설정하시면 됩니다.\r\n");
      out.write("9. 개인정보의 기술적·관리적 보호 대책 \r\n");
      out.write("회사는 이용자들의 개인정보를 취급함에 있어 개인정보가 분실, 도난, 누출, 변조 또는 훼손되지 않도록 안전성 확보를 위하여 다음과 같은 기술적/관리적 대책을 강구하고 있습니다.\r\n");
      out.write("  가. 비밀번호 암호화\r\n");
      out.write("  회원 아이디(ID)의 비밀번호는 암호화되어 저장 및 관리되고 있어 본인만이 알고 있으며, 개인정보의 확인 및 변경도 비밀번호를 알고 있는 본인에 의해서만 가능합니다.  \r\n");
      out.write("  나. 해킹 등에 대비한 대책\r\n");
      out.write("  회사는 해킹이나 컴퓨터 바이러스 등에 의해 회원의 개인정보가 유출되거나 훼손되는 것을 막기 위해 최선을 다하고 있습니다. 개인정보의 훼손에 대비해서 자료를 수시로 백업하고 있고, 최신 백신프로그램을 이용하여 이용자들의 개인정보나 자료가 누출되거나 손상되지 않도록 방지하고 있으며, 암호화통신 등을 통하여 네트워크상에서 개인정보를 안전하게 전송할 수 있도록 하고 있습니다. 그리고 침입차단시스템을 이용하여 외부로부터의 무단 접근을 통제하고 있으며, 기타 시스템적으로 보안성을 확보하기 위한 가능한 모든 기술적 장치를 갖추려 노력하고 있습니다.  \r\n");
      out.write("  다. 취급 직원의 최소화 및 교육\r\n");
      out.write("  회사의 개인정보관련 취급 직원은 담당자에 한정시키고 있고 이를 위한 별도의 비밀번호를 부여하여 정기적으로 갱신하고 있으며, 담당자에 대한 수시 교육을 통하여 개인정보취급방침의 준수를 항상 강조하고 있습니다.\r\n");
      out.write("10. 고지의 의무 \r\n");
      out.write("현 개인정보취급방침 내용상 추가, 삭제 및 수정이 있을 시에는 개정 최소 7일전부터 홈페이지를 통해 고지합니다. 다만 개인정보의 수집 및 활용, 제3자 제공 등과 같이 이용자 권리의 중요한 변경이 있을 경우에는 최소 30일 전에 고지합니다.\r\n");
      out.write("개인정보관리책임자 및 담당자의 연락처\r\n");
      out.write("귀하께서는 회사의 서비스를 이용하시며 발생하는 모든 개인정보보호 관련 민원을 개인정보관리책임자 혹은 담당부서로 신고하실 수 있습니다. 회사는 이용자들의 신고사항에 대해 신속하게 충분한 답변을 드릴 것입니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"myModal1\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal content-->\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        <h4 class=\"modal-title\">홈페이지 이용약관</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <p>제 1 장 총칙 \r\n");
      out.write("\r\n");
      out.write("제1조 (목적) \r\n");
      out.write("이 약관은 주식회사 인크(이하 “회사”)가 온라인으로 제공하는 서비스 및 이에 부수된 제 반 서비스(이하 “서비스”)의 이용과 관련하여 회사와 회원 간의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다. \r\n");
      out.write("\r\n");
      out.write("제 2 조 (용어의 정의) \r\n");
      out.write("① 이 약관에서 사용하는 용어의 정의는 다음과 같습니다. \r\n");
      out.write("1. “회사”라 함은 온라인을 통하여 서비스를 제공하는 사업자를 의미합니다.\r\n");
      out.write("2. “회원”이라 함은 회사의 서비스에 접속하여 이 약관에 따라 회사와 이용계약을 체결하여 회사가 제공하는 서비스를 이용하는 고객을 의미합니다.\r\n");
      out.write("3. “서비스”라 함은 회사가 회원에게 온라인으로 제공하는 온라인소액투자중개 서비스 및 이에 부수된 제반 서비스를 의미합니다.\r\n");
      out.write("4. “계정(ID)”이라 함은 회원의 식별과 서비스 이용을 위하여 회원이 선정하고 회사가 부여하는 문자, 숫자 또는 특수문자의 조합을 의미합니다.\r\n");
      out.write("5. “계정정보“라 함은 회원의 계정, 비밀번호, 성명 등 회원이 회사에 제공한 일반정보 및 서비스이용정보, 이용요금 결제상태 등 생성 정보를 통칭합니다.\r\n");
      out.write("6. “비밀번호”라 함은 회원이 부여 받은 계정과 일치되는 회원임을 확인하고 회원의 정보 및 권익보호를 위해 회원 자신이 선정하여 는 문자, 숫자 또는 특수문자의 조합을 의미합니다.\r\n");
      out.write("7. “콘텐츠”라 함은 회사가 서비스에 제공하는 문자, 문서, 그림, 음성, 음향, 영상 또는 이들의 조합으로 이루어진 모든 정보를 말합니다.\r\n");
      out.write("8. “게시물”이라 함은 회원이 서비스를 이용함에 있어 회원이 게시한 문자, 문서, 그림, 음성, 영상 또는 이들의 조합으로 이루어진 모든 정보를 말합니다.\r\n");
      out.write("② 이 약관에서 사용하는 용어의 정의는 제1항 각호에서 정하는 것을 제외하고는 관계법령 및 기타 일반적인 상관례에 의합니다.\r\n");
      out.write("\r\n");
      out.write("제 3 조 (회사정보 등의 제공) \r\n");
      out.write("회사는 다음 각 호의 사항을 서비스 초기화면이나 서비스 홈페이지에 게시하여, 회원이 이를 쉽게 알 수 있도록 합니다. 다만, 개인정보취급방침과 약관은 회원이 연결화면을 통하여 볼 수 있도록 할 수 있습니다. \r\n");
      out.write("1. 상호 및 대표자의 성명\r\n");
      out.write("2. 영업소 소재지 주소(회원의 불만을 처리할 곳의 주소 포함) 및 전자우편주소\r\n");
      out.write("3. 전화번호\r\n");
      out.write("4. 사업자등록번호\r\n");
      out.write("5. 홈페이지 이용약관\r\n");
      out.write("6. 서비스 이용약관\r\n");
      out.write("7. 개인정보취급방침\r\n");
      out.write("8. 투자위험고지\r\n");
      out.write("\r\n");
      out.write("제 4 조 (약관의 명시와 개정) \r\n");
      out.write("① 회사는 이 약관의 내용을 회원이 알 수 있도록 서비스 초기 화면이나 서비스 홈페이지에 게시하거나 연결화면을 제공하는 방법으로 회원에게 공지합니다.\r\n");
      out.write("② 회사는 회원이 회사와 이 약관의 내용에 관하여 질의 및 응답을 할 수 있도록 조치를 취합니다.\r\n");
      out.write("③ 회사는 서비스를 이용하고자 하는 자(이하 “이용자”라 한다)가 약관의 내용을 알 수 있도록 작성하고 약관에 동의하기에 앞서 약관에 정하여져 있는 내용 중 청약철회, 과오납금의 환급, 계약 해제ㆍ해지, 회사의 면책사항 및 회원에 대한 피해보상 등 중요한 내용을 회원이 알 수 있도록 합니다.\r\n");
      out.write("④ 회사는 「전자상거래 등에서의 소비자보호에 관한 법률」, 「약관의 규제에 관한 법률」, 「정보통신망이용촉진 및 정보보호 등에 관한 법률」, 「콘텐츠산업진흥법」 등 관련 법령에 위배하지 않는 범위에서 이 약관을 개정할 수 있습니다.\r\n");
      out.write("⑤ 회사가 약관을 개정할 경우에는 적용일자 및 개정내용, 개정사유 등을 명시하여 그 적용일자로부터 최소한 7일 이전(단, 회원에게 불리하거나 중대한 사항의 변경은 30일 이전)부터 그 적용일자 경과 후 상당한 기간이 경과할 때까지 초기화면 또는 초기화면과의 연결화면을 통해 공지합니다. 기존회원에게는 공지 외에 개정약관을 전자우편주소로 발송합니다.\r\n");
      out.write("⑥ 회사가 약관을 개정할 경우에는 개정약관 공지 후 개정약관의 적용에 대한 회원의 동의 여부를 확인합니다. 개정약관 공지시 회원이 동의 또는 거부의 의사표시를 하지 않으면 승낙한 것으로 간주하겠다는 내용도 함께 공지한 경우에는 회원이 약관 시행일까지 거부의사를 표시하지 않는다면 개정약관에 동의한 것으로 간주할 수 있습니다.\r\n");
      out.write("⑦ 회원이 개정약관의 적용에 동의하지 않는 경우 회사 또는 회원은 서비스 이용계약을 해지할 수 있습니다.이때, 회사는 계약해지로 인하여 회원이 입은 손해를 배상합니다.\r\n");
      out.write("\r\n");
      out.write("제 5 조 (약관 외 준칙) \r\n");
      out.write("이 약관에서 정하지 아니한 사항과 이 약관의 해석에 관하여는 「전자상거래 등에서의 소비자보호에 관한 법률」,「약관의 규제에 관한 법률」,「정보통신망이용촉진 및 정보보호 등에 관한 법률」,「콘텐츠산업진흥법」 등 관련 법령또는 상관례에 따릅니다. \r\n");
      out.write("제 6 조 (운영정책) \r\n");
      out.write("① 약관을 적용하기 위하여 필요한 사항과 회원의 권익을 보호하고 서비스 내 질서를 유지하기 위하여 회사는 약관에서 구체적 범위를 정하여 위임한 사항을 서비스 운영정책(이하 “운영정책”이라 합니다)으로 정할 수 있습니다.\r\n");
      out.write("② 회사는 운영정책의 내용을 회원이 알 수 있도록 서비스 초기 화면이나 서비스 홈페이지에 게시하거나 연결화면을 제공하는 방법으로 회원에게 공지하여야 합니다.\r\n");
      out.write("③ 회원의 권리 또는 의무에 중대한 변경을 가져오거나 약관 내용을 변경하는 것과 동일한 효력이 발생하는 운영정책 개정의 경우에는 제4조의 절차에 따릅니다. 단, 운영정책 개정이 다음 각 호의 어느 하나에 해당하는 경우에는 제2항의 방법으로 사전에 공지합니다.\r\n");
      out.write("1. 약관에서 구체적으로 범위를 정하여 위임한 사항을 개정하는 경우\r\n");
      out.write("2. 회원의 권리·의무와 관련 없는 사항을 개정하는 경우\r\n");
      out.write("3. 운영정책의 내용이 약관에서 정한 내용과 근본적으로 다르지 않고 회원이 예측가능한 범위 내에서 운영정책을 개정하는 경우\r\n");
      out.write("\r\n");
      out.write("제 2 장 이용계약의 체결 \r\n");
      out.write("제 7 조 (회원 계정(ID) 및 비밀번호) \r\n");
      out.write("① 회사는 회원에 대하여 회원의 정보 보호, 서비스 이용안내 등의 편의를 위해 회원이 선정한 일정한 문자, 숫자 또는 특수문자의 조합을 계정으로 부여합니다.\r\n");
      out.write("② 회사는 계정정보를 통하여 당해 회원의 서비스 이용가능 여부 등의 제반 회원 관리업무를 수행합니다.\r\n");
      out.write("③ 회원은 자신의 계정정보를 선량한 관리자로서의 주의 의무를 다하여 관리하여야 합니다. 회원이 본인의 계정정보를 소홀히 관리하거나 제3자에게 이용을 승낙함으로써 발생하는 손해에 대하여는 회원에게 책임이 있습니다.\r\n");
      out.write("④ 비밀번호의 관리책임은 회원에게 있으며, 회원이 원하는 경우에는 보안상의 이유 등으로 언제든지 변경이 가능합니다.\r\n");
      out.write("⑤ 회원은 정기적으로 비밀번호를 변경하여야 합니다.\r\n");
      out.write("\r\n");
      out.write("제 8 조 (회원 정보의 제공 및 변경) \r\n");
      out.write("① 회원은 이 약관에 의하여 회사에 정보를 제공하여야 하는 경우에는 진실된 정보를 제공하여야 하며, 허위정보 제공으로 인해 발생한 불이익에 대해서는 보호받지 못합니다.\r\n");
      out.write("② 회원은 개인정보관리화면을 통하여 언제든지 자신의 개인정보를 열람하고 수정할 수 있습니다. 다만, 서비스 관리를 위해 필요한 실명, 계정(ID) 등은 수정이 불가능합니다.\r\n");
      out.write("③ 회원은 회원가입 신청 시 기재한 사항이 변경되었을 경우 온라인으로 수정을 하거나 기타 방법으로 회사에 대하여 그 변경사항을 알려야 합니다.\r\n");
      out.write("④ 제2항의 변경사항을 회사에 알리지 않아 발생한 불이익에 대하여 회사는 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제 9 조 (개인정보의 보호 및 관리) \r\n");
      out.write("① 회사는 관계 법령이 정하는 바에 따라 계정정보를 포함한 회원의 개인정보를 보호하기 위해 노력합니다. 회원 개인정보의 보호 및 사용에 대해서는 관계법령 및 회사가 별도로 고지하는 개인정보취급방침이 적용됩니다.\r\n");
      out.write("② 서비스의 일부로 제공되는 개별 서비스를 제외한 것으로서 홈페이지 및 서비스별 웹사이트에서 단순히 링크된 제3자 제공의 서비스에 대하여는 회사의 개인정보취급방침이 적용되지 않습니다.\r\n");
      out.write("③ 회사는 회원의 귀책사유로 인하여 노출된 회원의 계정정보를 포함한 모든 정보에 대해서 일체의 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제 3 장 계약 당사자의 의무 \r\n");
      out.write("제 10 조 (회사의 의무) \r\n");
      out.write("① 회사는 관련 법령을 준수하고, 이 약관이 정하는 권리의 행사와 의무의 이행을 신의에 따라 성실하게 합니다.\r\n");
      out.write("② 회사는 회원이 안전하게 서비스를 이용할 수 있도록 개인정보(신용정보 포함)보호를 위해 보안시스템을 갖추어야 하며 개인정보취급방침을 공시하고 준수합니다. 회사는 이 약관 및 개인정보취급방침에서 정한 경우를 제외하고는 회원의 개인정보가 제3자에게 공개 또는 제공되지 않도록 합니다.\r\n");
      out.write("③ 회사는 계속적이고 안정적인 서비스의 제공을 위하여 서비스 개선을 하던 중 설비에 장애가 생기거나 데이터 등이 멸실된 때에는 천재지변, 비상사태, 현재의 기술로는 해결이 불가능한 결함 및 장애 등 부득이한 사유가 없는 한 지체 없이 이를 수리 또는 복구하도록 최선의 노력을 다합니다.\r\n");
      out.write("\r\n");
      out.write("제 11 조 (회원의 의무) \r\n");
      out.write("① 회원은 다음 행위를 하여서는 안 됩니다.\r\n");
      out.write("1. 신청 또는 변경 시 허위내용의 기재\r\n");
      out.write("2. 타인의 정보도용\r\n");
      out.write("3. 회사의 임직원, 운영자, 기타 관계자를 사칭하는 행위\r\n");
      out.write("4. 회사가 게시한 정보의 변경\r\n");
      out.write("5. 회사가 금지한 정보(컴퓨터 프로그램 등)의 송신 또는 게시\r\n");
      out.write("6. 회사가 제공 또는 승인하지 아니한 컴퓨터 프로그램이나 기기 또는 장치를 제작, 배포, 이용, 광고하는 행위\r\n");
      out.write("7. 회사와 기타 제3자의 저작권 등 지적재산권에 대한 침해\r\n");
      out.write("8. 회사 및 기타 제3자의 명예를 손상시키거나 업무를 방해하는 행위\r\n");
      out.write("9. 외설 또는 폭력적인 말이나 글, 화상, 음향, 기타 공서양속에 반하는 정보를 (회사의 사이트에)공개 또는 게시하는 행위\r\n");
      out.write("10. 서비스 데이터를 유상으로 처분하거나 권리의 객체로 하는 행위\r\n");
      out.write("11. 10호의 행위를 유도하거나 광고하는 행위\r\n");
      out.write("12. 회사의 동의 없이 영리, 영업, 광고, 정치활동 등을 목적으로 서비스를 사용하는 행위\r\n");
      out.write("13. 기타 관련 법령에서 금지하거나 선량한 풍속 기타 사회통념상 허용되지 않는 행위\r\n");
      out.write("② 회원은 이 약관의 규정, 이용안내 및 서비스와 관련하여 공지한 주의사항, 회사가 통지하는 사항 등을 확인하고 준수할 의무가 있습니다.\r\n");
      out.write("③ 회사는 제1항, 제2항 및 다음 각 호의 어느 하나에 해당하는 행위의 구체적인 유형을 운영정책에서 정할 수 있으며, 회원은 이를 준수할 의무가 있습니다.\r\n");
      out.write("1. 회원의 계정명, 기타 서비스상 사용하는 명칭에 대한 제한\r\n");
      out.write("2. 댓글이용에 대한 제한\r\n");
      out.write("3. 서비스 이용방법에 대한 제한\r\n");
      out.write("4. 기타 회원의 서비스 이용에 대한 본질적 권리를 침해하지 않는 범위 내에서 회사가 서비스 운영상 필요하다고 인정되는 사항\r\n");
      out.write("\r\n");
      out.write("제 4 장 서비스 이용 \r\n");
      out.write("제 12 조 (서비스의 변경 및 내용수정) \r\n");
      out.write("① 회원은 회사가 제공하는 서비스를 이 약관, 운영정책 및 회사가 설정한 서비스규칙에 따라 이용할 수 있습니다.\r\n");
      out.write("② 회사는 서비스 내용의 제작, 변경, 유지, 보수에 관한 포괄적인 권한을 가집니다.\r\n");
      out.write("③ 회사가 상당한 이유가 있는 경우에 운영상, 기술상의 필요에 따라 서비스 수정을 할 수 있으며, 서비스 수정을 하는 경우에는 변경 후 해당 서비스 화면 등을 통하여 공지합니다.\r\n");
      out.write("\r\n");
      out.write("제 13 조 (서비스의 제공 및 중단 등) \r\n");
      out.write("① 회사는 영업방침에 따라 정해진 시간 동안 서비스를 제공합니다.\r\n");
      out.write("② 제1항에도 불구하고, 다음 각 호의 어느 하나에 해당하는 경우에는 일정한 시간동안 서비스가 제공되지 아니할 수 있으며, 해당 시간 동안 회사는 서비스를 제공할 의무가 없습니다.\r\n");
      out.write("1. 컴퓨터 등 정보통신설비의 보수점검, 교체, 정기점검 또는 서비스 내용이나 서비스의 수정을 위하여 필요한 경우\r\n");
      out.write("2. 해킹 등의 전자적 침해사고, 통신사고, 회원들의 비정상적인 서비스 이용행태, 미처 예상하지 못한 서비스의 불안정성에 대응하기 위하여 필요한 경우\r\n");
      out.write("3. 관련 법령에서 특정 시간 또는 방법으로 서비스 제공을 금지하는 경우\r\n");
      out.write("4. 천재지변, 비상사태, 정전, 서비스 설비의 장애 또는 서비스 이용의 폭주 등으로 정상적인 서비스 제공이 불가능할 경우\r\n");
      out.write("5. 회사의 분할, 합병, 영업양도, 영업의 폐지, 당해 서비스의 수익 악화 등 회사의 경영상 중대한 필요에 의한 경우\r\n");
      out.write("③ 회사는 제2항 제1호의 경우, 매주 또는 격주 단위로 일정 시간을 정하여 서비스를 중지할 수 있습니다. 이 경우 회사는 최소한 24시간 전에 그 사실을 회원에게 서비스 초기 화면이나 서비스 홈페이지에 고지합니다.\r\n");
      out.write("④ 제2항 제2호의 경우, 회사는 사전 고지 없이 서비스를 일시 중지할 수 있습니다. 회사는 이러한 경우 그 사실을 서비스 초기 화면이나 서비스 홈페이지에 사후 고지할 수 있습니다.\r\n");
      out.write("⑤ 회사는 회사가 제공하는 무료서비스 이용과 관련하여 이용자에게 발생한 어떠한 손해에 대해서도 책임을 지지 않습니다. 다만, 회사의 고의 또는 중대한 과실로 인하여 발생한 손해의 경우는 제외합니다.\r\n");
      out.write("⑥ 제2항 제3호 내지 제5호의 경우에 회사는 기술상•운영상 필요에 의해 서비스 전부를 중단할 수 있으며, 사전에 공지하고 서비스의 제공을 중단할 수 있습니다. 사전에 공지할 수 없는 부득이한 사정이 있는 경우는 사후에 공지를 할 수 있습니다.\r\n");
      out.write("⑦ 회사가 부득이한 사유에 따라 서비스를 종료하는 경우 회원은 서비스 이용이 중단됨에 따른 손해배상을 청구할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("제 14 조 (정보의 수집 등) \r\n");
      out.write("① 회사는 서비스 내에서 회원간에 이루어지는 모든 게시 내용을 저장ㆍ보관할 수 있습니다. 회사는 회원간의 분쟁 조정, 민원 처리 또는 서비스 질서의 유지를 위하여 회사가 필요하다고 판단하는 경우에 한하여 본 정보를 열람하도록 할 것이며, 본 정보는 회사만이 보유하고 법령으로 권한을 부여 받지 아니한 제3자는 절대로 열람할 수 없습니다. 회사는 해당 정보를 열람하기 전에 게시내용의 열람이 필요한 사유 및 열람 범위를 개인에게 사전 고지하기로 합니다. 다만, 계정도용, 현금거래, 언어폭력, 서비스 내 사기 등 기망행위, 버그 악용, 기타 현행 법령 위반행위 및 이 약관 제11조에서 정하는 중대한 약관위반 행위의 조사, 처리, 확인 및 이의 구제와 관련하여 회원의 게시 정보를 열람해야 할 필요가 있는 경우에는, 사후에 게시정보가 열람된 개인들에 대하여 열람한 사유와 열람한 정보 중 본인과 관련된 부분을 고지하기로 합니다.\r\n");
      out.write("② 회사는 서비스 운영 및 프로그램 안정화 등 서비스 품질 개선을 위하여 회원 PC 등 단말기 설정 및 사양 정보를 수집·활용할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 15 조 (저작권 등의 귀속) \r\n");
      out.write("① 서비스 내 회사가 제공하는 모든 콘텐츠에 대한 저작권 기타 지적재산권은 회사의 소유입니다.\r\n");
      out.write("② 회원은 회사가 제공하는 서비스를 이용함으로써 얻은 정보 중 회사 또는 제공업체에 지적재산권이 귀속된 정보를 회사 또는 제공업체의 사전승낙 없이 복제, 전송, 출판, 배포, 방송 기타 방법에 의하여 영리목적으로 이용하거나 제3자에게 이용하게 하여서는 안 됩니다.\r\n");
      out.write("③ 회원은 서비스내에서 보여지거나 서비스와 관련하여 회원 또는 다른 이용자가 서비스 클라이언트 또는 서비스를 통해 업로드 또는 전송하는 문자, 이미지, 사운드 및 모든 자료 및 정보(이하 '이용자 콘텐츠'라 한다.)에 대하여 회사가 다음과 같은 방법과 조건으로 이용하는 것을 허락합니다.\r\n");
      out.write("1. 해당 이용자 콘텐츠를 이용, 편집 형식의 변경 및 기타 변형하는 것(공표, 복제, 공연, 전송, 배포, 방송, 2차적 저작물 작성 등 어떠한 형태로든 이용 가능하며, 이용기간과 지역에는 제한이 없음)\r\n");
      out.write("2. 이용자 콘텐츠를 제작한 이용자의 사전 동의 없이 거래를 목적으로 이용자 콘텐츠를 판매, 대여, 양도 행위를 하지 않음\r\n");
      out.write("④ 서비스내에서 보여지지 않고 서비스와 일체화되지 않은 회원의 이용자 콘텐츠(예컨대, 일반게시판 등에의 게시물)에 대하여 회사는 회원의 명시적인 동의가 없이 상업적으로 이용하지 않으며, 회원은 언제든지 이러한 이용자 콘텐츠를 삭제할 수 있습니다.\r\n");
      out.write("⑤ 회사는 회원이 게시하거나 등록하는 서비스 내의 게시물, 게시 내용에 대해 제 11조에서 규정하는 금지행위에 해당된다고 판단되는 경우, 사전통지 없이 이를 삭제하거나 이동 또는 등록을 거부할 수 있습니다.\r\n");
      out.write("⑥ 제3항은 회사가 서비스를 운영하는 동안 유효하며 회원탈퇴 후에도 지속적으로 적용됩니다.\r\n");
      out.write("\r\n");
      out.write("제 5 장 계약 해제·해지 및 이용제한 \r\n");
      out.write("제 16 조 (회사의 해제 및 해지) \r\n");
      out.write("① 회사는 회원이 이 약관에서 정한 회원의 의무를 위반한 경우에는 회원에 대한 사전 통보 후 계약을 해지할 수 있습니다. 다만, 회원이 현행법 위반 및 고의 또는 중대한 과실로 회사에 손해를 입힌 경우에는 사전 통보 없이 이용계약을 해지할 수 있습니다.\r\n");
      out.write("② 회사가 이용계약을 해지하는 경우 회사는 회원에게 서면, 전자우편 또는 이에 준하는 방법으로 다음 각 호의 사항을 회원에게 통보합니다.\r\n");
      out.write("1. 해지사유\r\n");
      out.write("2. 해지일\r\n");
      out.write("③ 제1항 단서의 경우, 회원은 유료서비스의 사용권한을 상실하고 이로 인한 환불 및 손해배상을 청구할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("제 17 조 (회원에 대한 서비스 이용제한) \r\n");
      out.write("① 회사는 회원에게 다음 각 호의 구분에 따라 회원의 서비스 이용을 제한할 수 있습니다.\r\n");
      out.write("이용제한이 이루어지는 구체적인 회원의 의무위반 사유는 서비스의 운영정책에서 정하기로 합니다.\r\n");
      out.write("1. 계정 이용제한 : 일정기간 또는 영구히 회원 계정의 이용을 제한\r\n");
      out.write("2. 회원 이용제한 : 일정기간 또는 영구히 회원의 서비스 이용을 제한\r\n");
      out.write("② 회사의 이용제한이 정당한 경우에 회사는 이용제한으로 인하여 회원이 입은 손해를 배상하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("제 18 조 (잠정조치로서의 이용제한)\r\n");
      out.write("회사는 다음 각 호에 해당하는 문제에 대한 조사가 완료될 때까지 계정을 정지할 수 있습니다. \r\n");
      out.write("회사는 다음 각 호에 해당하는 문제에 대한 조사가 완료될 때까지 계정을 정지할 수 있습니다.\r\n");
      out.write("1. 계정이 해킹 또는 도용 당하였다는 정당한 신고가 접수된 경우\r\n");
      out.write("2. 불법프로그램 사용자, 작업장 등 위법행위자로 합리적으로 의심되는 경우\r\n");
      out.write("3. 그 밖에 위 각호에 준하는 사유로 계정의 잠정조치가 필요한 경우\r\n");
      out.write("\r\n");
      out.write("제 6 장 손해배상 등 \r\n");
      out.write("제 19 조 (손해배상) \r\n");
      out.write("① 회사가 고의 또는 중과실로 회원에게 손해를 끼친 경우, 손해에 대하여 배상할 책임이 있습니다.\r\n");
      out.write("② 회원이 본 약관을 위반하거나 위법한 행위로 회사에 손해를 끼친 경우, 회원은 회사에 대하여 그 손해에 대하여 배상할 책임이 있습니다. \r\n");
      out.write("\r\n");
      out.write("제 20 조 (회사의 면책) \r\n");
      out.write("① 회사는 전시, 사변, 천재지변, 비상사태, 현재의 기술로는 해결이 불가능한 기술적 결함 기타 불가항력적 사유로 서비스를 제공할 수 없는 경우에는 책임이 면제됩니다.\r\n");
      out.write("② 회사는 회원의 귀책사유로 인한 서비스의 중지, 이용장애 및 계약해지에 대하여 책임이 면제됩니다.\r\n");
      out.write("③ 회사는 기간통신 사업자가 전기통신서비스를 중지하거나 정상적으로 제공하지 아니하여 회원에게 손해가 발생한 경우에 대해서 회사의 고의 또는 중대한 과실이 없는 한 책임이 면제됩니다.\r\n");
      out.write("④ 회사는 사전에 공지된 서비스용 설비의 보수, 교체, 정기점검, 공사 등 부득이한 사유로 서비스가 중지되거나 장애가 발생한 경우에 대해서 회사의 고의 또는 중대한 과실이 없는 한 책임이 면제됩니다.\r\n");
      out.write("⑤ 회사는 회원의 컴퓨터 환경으로 인하여 발생하는 제반 문제 또는 회사의 고의 또는 중대한 과실이 없는 네트워크 환경으로 인하여 발생하는 문제에 대해서 책임이 면제됩니다.\r\n");
      out.write("⑥ 회사는 회원 또는 제3자가 서비스 내 또는 웹사이트 상에 게시 또는 전송한 정보, 자료, 사실의 신뢰도, 정확성 등의 내용에 대해서는 회사의 고의 또는 중대한 과실이 없는 한 책임이 면제됩니다.\r\n");
      out.write("⑦ 회사는 회원 상호간 또는 회원과 제3자간에 서비스를 매개로 발생한 분쟁에 대해 개입할 의무가 없으며 이로 인한 손해를 배상할 책임도 없습니다.\r\n");
      out.write("⑧ 회사가 제공하는 서비스 중 무료서비스의 경우에는 회사의 고의 또는 중대한 과실이 없는 한 회사는 손해배상을 하지 않습니다.\r\n");
      out.write("⑨ 본 서비스 중 일부의 서비스는 다른 사업자가 제공하는 서비스를 통하여 제공될 수 있으며, 회사는 다른 사업자가 제공하는 서비스로 인하여 발생한 손해 등에 대해서는 회사의 고의 또는 중대한 과실이 없는 한 책임이 면제됩니다.\r\n");
      out.write("⑩ 회사는 회원의 컴퓨터 오류에 의한 손해가 발생한 경우 또는 신상정보 및 전자우편주소를 부정확하게 기재하거나 미기재하여 손해가 발생한 경우에 대하여 회사의 고의 또는 중대한 과실이 없는 한 책임이 면제됩니다.\r\n");
      out.write("⑪ 회사는 관련 법령, 정부 정책 등에 따라 서비스 또는 회원에 따라 서비스 이용시간 등을 제한할 수 있으며, 이러한 제한사항 및 제한에 따라 발생하는 서비스 이용 관련 제반사항에 대해서는 책임이 면제됩니다.\r\n");
      out.write("\r\n");
      out.write("제 21 조 (회원에 대한 통지) \r\n");
      out.write("① 회사가 회원에게 통지를 하는 경우 회원이 지정한 전자우편주소, 전자메모 등으로 할 수 있습니다.\r\n");
      out.write("② 회사는 회원 전체에게 통지를 하는 경우 서비스 초기화면에 게시하거나 팝업화면 등을 제시함으로써 제1항의 통지에 갈음할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제 22 조 (재판권 및 준거법) \r\n");
      out.write("본 약관은 대한민국 법률에 따라 규율되고 해석되며, 회사와 회원간에 발생한 분쟁으로 소송이 제기되는 경우, 법령에 정한 절차에 따른 법원을 관할 법원으로 합니다.\r\n");
      out.write("\r\n");
      out.write("부칙 \r\n");
      out.write("제1조 이 약관은 2015년 12월 1일부터 적용됩니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
