/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-08-02 07:44:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.establish;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contentDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t<title>프로젝트 상세보기</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"../js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/include/css/contentDetail2.css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/common.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form class=\"project_intro_index\" id=\"project_intro_index\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"intro_index\" name=\"intro_index\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 타이틀 -->\r\n");
      out.write("\t\t<div class=\"b-header b-header_centered_yes\">\r\n");
      out.write("\t\t\t<div class=\"b-header__inner\">\r\n");
      out.write("\t\t\t\t<h1 class=\"headline\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\t\t\t\t<p class=\"deck text-size_xl\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_subtitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<!-- 탭 메뉴 -->\r\n");
      out.write("\t\t<div class=\"i-nav-local is-hidden\"></div>\r\n");
      out.write("\t\t<nav class=\"b-nav-local in-nav-local js-nav-local\">\r\n");
      out.write("\t\t\t<div class=\"b-nav-local__inner\">\r\n");
      out.write("\t\t\t\t<ul class=\"b-menu b-menu_horiz_yes b-menu_stroke_yes b-menu_align_center\">\r\n");
      out.write("\t\t\t\t\t<li class=\"b-menu__item\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <a href=\"/\" data-ps=\"true\" class=\"b-menu__item__link is-selected\"> -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"b-menu__item__link is-selected\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>프로젝트 소개</span>\r\n");
      out.write("\t\t\t\t\t\t<!-- </a> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"b-menu__item\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/establish/contentReply.do\" data-ps=\"true\" class=\"b-menu__item__link\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>댓글 ( <span class=\"js-channelCounter\">0</span> )</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 본문 -->\r\n");
      out.write("\t\t<div class=\"b-content b-content--clean\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t    <!-- 프로젝트 이미지 -->\r\n");
      out.write("\t\t\t\t<div class=\"b-main\" id=\"project_show_section_js\"> \r\n");
      out.write("\t\t\t\t\t<figure class=\"b-video js-video\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"b-video__poster js-video-poster\" src=\"https://tumblbug-pci.imgix.net/eb663c81ddd2d3fd2824f755e800244404371d1a/ba66876acd8823742bb2b717b5d7a00a5bc39a79/a27a928b0684738485a9fa6a22cec8fb95ca922b/3ae144dbfb85dc4e499bdd329e7c28adc492e371.jpg?ixlib=rb-1.1.0&amp;w=620&amp;h=465&amp;auto=format%2Ccompress&amp;lossless=true&amp;fit=crop&amp;s=f5cfdad5027b866a486d8ab404e8728f\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"b-content-description typeset-proto-v2 js-project_desc\" style=\"margin-top: 28px;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"detail_form_01\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"detail_form_line\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h3>▶ 프로젝트 소개</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_details}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"detail_form_02\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"detail_form_line\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h3>&lt;시놉시스&gt;</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<blockquote>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_synopsis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</blockquote>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"detail_form_01\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"detail_form_line\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h3>▶ 프로젝트 계획</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_plan}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"detail_form_01\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"detail_form_line\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h3>▶ 프로젝트 목표</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_purpose}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"detail_form_line\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t<div class=\"b-panel b-panel--theme_clean b-panel--rounded_yes box has-pad-horiz-dot5\">\r\n");
      out.write("\t\t\t\t\t\t<strong class=\"box text-size_xs\">이 프로젝트의 환불 및 교환 정책</strong>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-size_xs\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_refund}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t<!-- 기획자 정보 -->\r\n");
      out.write("\t\t\t\t<div class=\"b-sidebar\" role=\"complementary\" >\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t<dl class=\"b-campaign_stats\"> \r\n");
      out.write("\t\t\t\t\t\t<dt class=\"b-campaign_stats__title\">목표 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_purpose}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('중');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_report}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("% 모임</dt> \r\n");
      out.write("\t\t\t\t\t\t<dd class=\"b-campaign_stats__value\"> \r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"b-campaign_stats__value-figure\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_fund}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span class=\"b-campaign_stats__value-unit\">원</span>\r\n");
      out.write("\t\t\t\t\t\t</dd> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<dt class=\"b-campaign_stats__title\">남은 시간</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd class=\"b-campaign_stats__value\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"b-campaign_stats__value-figure\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_dday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span class=\"b-campaign_stats__value-unit\">일</span>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<dt class=\"b-campaign_stats__title\">후원자</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd class=\"b-campaign_stats__value\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"b-campaign_stats__value-figure\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span class=\"b-campaign_stats__value-unit\">명</span>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t<a href=\"/intro/reward.do\" class=\"c-pledge_button js-show-pledge-button\"><span class=\"c-pledge_button__label\">프로젝트 밀어주기</span><span class=\"c-pledge_button__help\"> 최소금액은 1,000원입니다.</span></a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p class=\"b-pledge_blurb js-pledge_blurb\">결제는 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 자정까지 최소 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${donationDetail.dona_purpose}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원이 모여야만 다함께 진행됩니다</p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div data-scroll='sticky' data-top-offset='13' data-bottom-offset='39'  data-remote-body='.b-sidebar' >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"b-panel box\" data-ui-component=\"profile-card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"b-panel__head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"b-panel__body has-no-pad\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"b-profile_card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"b-profile_card__title\">프로젝트 크리에이터</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"b-profile_card__identity\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"b-avatar lfloat\" style=\"width: 62px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"b-avatar__frame b-avatar__frame--bordered\" style=\"width:62px; height:62px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"B64be9e0b3922aeabf47bfac38e9baf892e7b064.jpg?ixlib=rb-1.1.0&amp;w=100&amp;h=125&amp;auto=format%2ccompress&amp;fit=facearea&amp;facepad=2\" class=\"b-avatar__pic\" src=\"https://tumblbug-upi.imgix.net/b64be9e0b3922aeabf47bfac38e9baf892e7b064.jpg?ixlib=rb-1.1.0&amp;w=100&amp;h=125&amp;auto=format%2Ccompress&amp;fit=facearea&amp;facepad=2.0&amp;ch=Save-Data&amp;mask=ellipse&amp;s=a1c17f2d47ad41cefeb8aec75cfa695a\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"b-profile_card__name_area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"b-profile_card__name_area__middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"b-profile_card__name_area__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"[ yoke yoke--theme_creator ]\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plannerDetail.plan_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"b-profile_card__location\"><i class=\"b-fontello b-fontello--location \"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${plannerDetail.plan_area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"u-clear\"></div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"b-profile_card__contacts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_project}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/list.do\" class=\"b-profile_card__contact_button js-newMessage\">문의하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"u-clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul><!-- b-profile_card --> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"i-presents\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"[ b-panel b-panel--theme_board b-panel--rounded_yes ] ui-present-card box b-panel--selectable_yes\" data-selectable=\"true\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"b-panel__head\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"b-panel__title\">프로젝트 후원자분들께</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!--.b-panel__head-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"b-panel__body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"ui-present-card__description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introDetail.intro_effect}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!--.b-panel__body-->\r\n");
      out.write("\t\t\t\t\t\t\t</li><!--.b-panel-->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div><!--b-sidebar-->\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
