/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-08-02 00:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.establish;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t<title>프로젝트 올리기 공지</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"../js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* alert(\"회원번호 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.blancheUser.us_index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\n회원ID : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.blancheUser.us_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"); */\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#app_btn').click(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(\"input[name='agree']:checked\").val() == \"Y\") {\r\n");
      out.write("\t\t\t\t\t\tvar login = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.blancheUser.us_index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\tif (login != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"/establish/applicationForm.do\";\r\n");
      out.write("\t\t\t\t\t\t\t//location.href=\"/establish/applicationDetailForm.do?app_index=23\";\r\n");
      out.write("\t\t\t\t\t\t\t//location.href=\"/establish/projectMyPage.do?app_index=23\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"로그인이 필요한 메뉴입니다.\\n로그인 후 다시 이용해 주시기 바랍니다.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/applicationForm.do\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/applicationDetailForm.do?app_index=3\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/contentDetail.do\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/applicationAdminList.do\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/projectAdminList.do\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/applicationMyPage.do?us_index=23\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/contentReply.do\";\r\n");
      out.write("\t\t\t\t\t\t//location.href=\"/establish/projectMyPage.do?us_index=3\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"위 내용을 모두 읽고 이해하셨으면 체크해주세요\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}); //end ready()\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- contents 시작-->\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<!-- 프로젝트 신청 시작 -->\r\n");
      out.write("\t\t<div class=\"prjOFA\">\r\n");
      out.write("\t\t\t<!-- 프로젝트 신청하기-->\r\n");
      out.write("\t\t\t<div class=\"innerAct\">\r\n");
      out.write("\t\t\t\t<div class=\"join_bg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"join\">\r\n");
      out.write("\t\t\t\t\t\t<h2>프로젝트 올리기</h2>\r\n");
      out.write("\t\t\t\t\t\t<p><em>안녕하세요! Blanche에서 프로젝트를 신청하기 전<br/>\r\n");
      out.write("\t\t\t\t\t\t\t아래를 읽어주시고 프로젝트 개설을 신청해주세요!</em></p>\r\n");
      out.write("\t\t\t\t\t\t<p>Blanche는 더불어 사는 사회를 지향하고 사회를 아름답게 바꾸는 프로젝트를 소개합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t개인이나 단체, 기업 등 프로젝트 신청 자격을 한정하지 않습니다.<br/>\r\n");
      out.write("\t\t\t\t\t\t\t단, 프로젝트의 내용이 개인의 취미생활을 위해 또는 어떤 사업에나  사용할 수 있는 자금마련이<br/>\r\n");
      out.write("\t\t\t\t\t\t\t아니라 사회를 바꾸고 변화시키는데 기여하고 그래서 보다 많은 분들에게<br/>\r\n");
      out.write("\t\t\t\t\t\t\t공감을 일으킬 수 있는 프로젝트이기를 희망합니다.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>내용이 완성되지 않아도, 프로젝트에 대한 추진 의지와 실행력이 있다면 신청하세요.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>Blanche의 프로젝트매니저가 상담하고 방문하여 함께 프로젝트를 다듬어드리고<br/>\r\n");
      out.write("\t\t\t\t\t\t   펀딩이 성공할 수 있도록 도와드리겠습니다. </p>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p style=\"padding-top: 15px\"><input type=\"checkbox\" class=\"chk\" name=\"agree\" value=\"Y\" />&nbsp;<span style='display:inline-block; margin-top:-1px'>위의 내용을 읽었습니다.</span></p>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"app_btn\" style=\"margin-top:15px;\">프로젝트 신청하기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 프로젝트 신청 끝 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- contents 끝-->\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
