/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-07-20 05:19:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t<title>게시판 상세보기</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t<script src=\"../js/html5shiv.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"/include/css/common.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/include/css/board.css\"> -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/common.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/include/js/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar butChk = 0;\t// 수정버튼과 삭제버튼을 구별하기 위한 변수\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$(\"#pwdChk\").hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 첨부파일 이미지 보여주기 위한 속성 추가 */\r\n");
      out.write("\t\t\t\tvar file = \"<c:out value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\";\r\n");
      out.write("\t\t\t\tif (file != \"\") {\r\n");
      out.write("\t\t\t\t\t$(\"#fileImage\").attr({\r\n");
      out.write("\t\t\t\t\t\tsrc:\"/uploadStorage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\twidth:\"450px\",\r\n");
      out.write("\t\t\t\t\t\theight:\"200px\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 수정 버튼 클릭 시 처리 이벤트 */\r\n");
      out.write("\t\t\t\t$(\"#updateForm\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t\t$(\"#msg\").text(\"작성시 입력한 비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\tbutChk = 1;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 삭제 버튼 클릭 시 처리 이벤트 */\r\n");
      out.write("\t\t\t\t$(\"#boardDelete\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#pwdChk\").show();\r\n");
      out.write("\t\t\t\t\t$(\"#msg\").text(\"작성시 입력한 비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\tbutChk = 2;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 비밀번호 확인 버튼 클릭 시 처리 이벤트 */\r\n");
      out.write("\t\t\t\t$(\"#pwdBut\").click(function() {\r\n");
      out.write("\t\t\t\t\tpwdConfirm();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* 목록 버튼 클릭 시 처리 이벤트 */\r\n");
      out.write("\t\t\t\t$(\"#boardList\").click(function() {\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/board/boardList.do\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* 비밀번호 확인 버튼 클릭시 실질적인 처리 함수 */\r\n");
      out.write("\t\t\tfunction pwdConfirm() {\r\n");
      out.write("\t\t\t\tif (!chkSubmit($('#b_pwd'), \"비밀번호를\")) return;\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$.ajax ({\r\n");
      out.write("\t\t\t\t\t\turl : \"/board/pwdConfirm.do\",\t// 전송 url\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\t// 전송 시 method 방식\r\n");
      out.write("\t\t\t\t\t\tdata : $(\"#f_pwd\").serialize(),\t// 폼전체 데이터 전송\r\n");
      out.write("\t\t\t\t\t\t/* dataType : \"text\", */\r\n");
      out.write("\t\t\t\t\t\terror : function() {\t// 실행시 오류가 발생하였을 경우\r\n");
      out.write("\t\t\t\t\t\t\talert('시스템 오류 입니다. 관리자에게 문의 하세요');\r\n");
      out.write("\t\t\t\t\t\t},\t// 정상적으로 실행이 되었을 경우\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(resultData) {\r\n");
      out.write("\t\t\t\t\t\t\tvar goUrl=\"\";\t// 이동할 경로를 저장할 변수\r\n");
      out.write("\t\t\t\t\t\t\tif (resultData == 0) {\t// 일치하지 않는 경우\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#msg\").text(\"작성시 입력한 비밀번호가 일치하지 않습니다.\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#b_pwd\").select();\r\n");
      out.write("\t\t\t\t\t\t\t} else if (resultData == 1) {\t// 일치할 경우\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#msg\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\tif (butChk == 1) {\t// 수정버튼 클릭시\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoUrl = \"/board/updateForm.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\t} else if (butChk == 2) {\t// 삭제버튼 클릭시\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoUrl = \"/board/boardDelete.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#f_data\").attr(\"action\", goUrl);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#f_data\").submit();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"contentContainer\">\r\n");
      out.write("\t\t\t<div class=\"contentTit\"><h3>게시판 상세보기</h3></div>\r\n");
      out.write("\t\t\t<form name=\"f_data\" id=\"f_data\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"b_num\" id=\"b_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"b_file\" id=\"b_file\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_file}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<table id=\"boardPwdBut\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"btd1\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pwdChk\">\r\n");
      out.write("\t\t\t\t\t\t\t<form name=\"f_pwd\" id=\"f_pwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"b_num\" id=\"b_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"b_pwd\" id=\"l_pwd\">비밀번호 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"b_pwd\" id=\"b_pwd\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" id=\"pwdBut\" value=\"확인\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"btd2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"수정\" id=\"updateForm\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"삭제\" id=\"boardDelete\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"목록\" id=\"boardList\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"contentTB\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"17%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"33%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"17%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"33%\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"ac\">작성자</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"ac\">작성일</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"ac\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"ac vm\">내용</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"ac vm\">첨부파일 이미지</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><img id=\"fileImage\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
